# Copyright (c) RentalManager. All Rights Reserved.
# Licensed under the MIT License. See LICENSE in the project root for license information.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: core-backend
spec:
  template:
    spec:
      containers:
      - name: core-backend
        resources:
          requests:
            cpu: 1000m
            memory: 1Gi
          limits:
            cpu: 4000m
            memory: 4Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rentalmanager-frontend
spec:
  template:
    spec:
      containers:
      - name: rentalmanager-frontend
        resources:
          requests:
            cpu: 200m
            memory: 256Mi
          limits:
            cpu: 1000m
            memory: 1Gi

