# Copyright (c) RentalManager. All Rights Reserved.
# Licensed under the MIT License. See LICENSE in the project root for license information.

apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: core-backend-hpa
spec:
  minReplicas: 5
  maxReplicas: 20
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: rentalmanager-frontend-hpa
spec:
  minReplicas: 5
  maxReplicas: 20

